# Generated by Django 3.1 on 2020-09-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgapi', '0005_auto_20200905_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
